#!/bin/bash
set -euo pipefail
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"
CONFIGURATION="${1:-release}"
if [[ "$CONFIGURATION" != "release" && "$CONFIGURATION" != "debug" ]]; then
  echo "Aufruf: scripts/build-app.sh [release|debug]" >&2
  exit 1
fi
swift build -c "$CONFIGURATION"
BIN_DIR="$(swift build -c "$CONFIGURATION" --show-bin-path)"
# Sign outside synced Documents folders: File Provider may otherwise attach
# FinderInfo between xattr cleanup and codesign, invalidating the app bundle.
STAGING_DIR="$(mktemp -d "${TMPDIR:-/tmp}/snappile-build.XXXXXX")"
trap 'rm -rf "$STAGING_DIR"' EXIT
APP_DIR="$STAGING_DIR/SnapPile.app"
OUTPUT_APP="$PROJECT_DIR/outputs/SnapPile.app"
mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources" "$PROJECT_DIR/work" "$PROJECT_DIR/outputs"
cp "$BIN_DIR/SnapPile" "$APP_DIR/Contents/MacOS/SnapPile"
cp Support/Info.plist "$APP_DIR/Contents/Info.plist"
swift scripts/make-icon.swift "$PROJECT_DIR/work/AppIcon.iconset"
iconutil -c icns "$PROJECT_DIR/work/AppIcon.iconset" -o "$APP_DIR/Contents/Resources/AppIcon.icns"
xattr -cr "$APP_DIR"
SIGNING_IDENTITY="${SNAPPILE_SIGNING_IDENTITY:--}"
codesign --force --sign "$SIGNING_IDENTITY" --identifier de.wdnhfr.snappile "$APP_DIR"
codesign --verify --strict "$APP_DIR"
# This destination is generated by this script and contains no user data.
rm -rf "$OUTPUT_APP"
ditto --norsrc --noextattr "$APP_DIR" "$OUTPUT_APP"
ditto -c -k --norsrc --noextattr --keepParent "$APP_DIR" "$PROJECT_DIR/outputs/SnapPile-macOS.zip"
echo "App erstellt: $OUTPUT_APP"
echo "Geprüftes App-Archiv: $PROJECT_DIR/outputs/SnapPile-macOS.zip"
